language: bash
services: docker

env:
  - VERSION=6.4 EXTRA_TAGS="-t latest"
  - VERSION=6.3
  - VERSION=6.2.1
  - VERSION=6.1.0
  - VERSION=6.0.0

script:
  - |
    docker build . -t "$VERSION" \
      --build-arg version=$VERSION \

after_script:
  - docker images
